String.prototype.fulltrim=function(){return this.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,'').replace(/\s+/g,' ');};

// Generated by CoffeeScript 1.6.2
(function() {
  // var io;




  io = require('socket.io').listen(8080);

  io.sockets.on('connection', function(socket) {
    var sendData;

    sendData = function(power) {
      return socket.emit('newReading', {
        power: power
      });
    };

    var net = require('net');
    var client = net.connect({
        port: 1234,
        host: "192.168.1.1"
      },
      function() { //'connect' listener
        console.log('client connected');
      });
    client.on('data', function(data) {
      console.log(data.toString());
      // power 1 44.4;
      var string = data.toString();
      power = string.split(" ")[2];


      var readingType = string.split(" ")[0];
      console.log(readingType);
      if (readingType === "power") {

        power = power.fulltrim();
        power = power.replace(/;/, '');

        console.log(power);

        var powerNum = parseInt(power, 10);

        sendData(powerNum);

      }
    });

  });






}).call(this);
